name: Build and Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "README.md"
      - "scripts/docs.sh"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc
        run: |
          sudo apt-get install -y pandoc

      - name: Build documentation
        run: |
          ./scripts/docs.sh build

      - name: Verify build output
        run: |
          if [ ! -d "./docs/build" ]; then
            echo "Error: docs directory not found after build"
            exit 1
          fi
          if [ ! -f "./docs/build/index.html" ]; then
            echo "Error: index.html not found in docs directory"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: docs
          commit_message: "docs: update documentation"
